on:
  push:
    branches: [master]
  pull_request:
name: Tests
jobs:
  tests:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Install compose
        run: |
          sudo curl -SL https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
          sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
          sudo chmod +x /usr/bin/docker-compose
          docker compose version
      - name: Run tests
        run: make test-dockerized
      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash)
